schemaVersion: "2.0.0"
commandTests:
- name: jre
  command: java
  args: ["-version"]
  expectedError: ['openjdk version "17.0.7"*']
- name: openssl
  command: apt
  args: ["list", "openssl"]
  expectedOutput: ['.*1.1.1n-0\+deb11u3*.']
fileExistenceTests:
- name: hive-home
  path: /opt/hive
  shouldExist: true
  uid: 1002
  gid: 0
- name: metastore-site.xml
  path: /opt/hive/conf/metastore-site.xml
  shouldExist: true
- name: log4j2.properties
  path: /opt/hive/conf/metastore-log4j2.properties
  shouldExist: true
#- name: aws-java-sdk-bundle-jar
#  path: /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.262.jar
#  shouldExist: true
#- name: hadoop-aws-jar
#  path: /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.4.jar
#  shouldExist: true
metadataTest:
  env:
  - key: JAVA_HOME
    value: /usr/lib/jvm/zulu17
  - key: HADOOP_HOME
    value: /opt/hadoop
  - key: HIVE_HOME
    value: /opt/hive
  exposedPorts: ["9083"]
  workdir: "/opt/hive"
  entrypoint: ["sh", "-c", "/opt/hive/entrypoint.sh"]
  cmd: []
